---
galaxy_info:
  author: Dan Carr
  description: Ansible profile role for developers
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
dependencies:
  - profile-all
  - roderik.superlumic-homebrew
